name: Issue Automation
description: Validate issue templates, detect duplicates and auto-assign issues.
author: Dtar380

inputs:
  token:
    description: "GitHub token with repo scope"
    required: true

  repo:
    description: "Repository in the format 'owner/repo'"
    required: true

  duplicate_threshold:
    description: "Similarity threshold for duplicate detection (0-100)"
    required: false
    default: "80"

  comment_templates_path:
    description: "Path to comment templates"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.token }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - run: python ${{ github.action_path }}/src/main.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ inputs.repo }}
        DUPLICATE_THRESHOLD: ${{ inputs.duplicate_threshold }}
        TEMPLATES_DIR: ${{ inputs.comment_templates_path }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
